### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by zhangzhousuper** [AdamYuan/VkNRC#2]
Hi I cannot build shader_u32 cuz of the cmake custom build,  Could u help be to figure it out?

![img_v3_02ef_4b6b0f03-861d-410e-9745-f92bdd669c5g](https://github.com/user-attachments/assets/63061c7a-d661-4c64-b56a-7c5f83e4ebd4)

**Comment by AdamYuan** [comment]
Did you have glslc or vulkan-sdk installed?
also, please try the newest commit, and there might be fewer issues about shader compilation.
